# Generated by Django 4.2.7 on 2023-11-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='insignia',
            name='obtenida',
            field=models.BooleanField(default=False),
        ),
    ]
