# Generated by Django 4.2.4 on 2023-11-05 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_insignia_obtenida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insignia',
            name='project',
        ),
    ]
