# Generated by Django 4.2.4 on 2023-11-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_insignia_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='insignia',
            name='imagen',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
