# Generated by Django 4.2.4 on 2023-11-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_insignias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='insignias',
            field=models.ManyToManyField(blank=True, to='myapp.insignia'),
        ),
    ]
