# Generated by Django 4.2.4 on 2023-11-05 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_user_insignias'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInsignias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insignia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.insignia')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
