# Generated by Django 4.2.4 on 2023-11-06 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_userinsignias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
