# Generated by Django 4.2.4 on 2023-11-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insignia',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
