# Generated by Django 4.2.4 on 2023-11-06 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_insignia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insignia',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
