# Generated by Django 4.2.7 on 2023-11-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_user_insignias_insignia_portador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insignia',
            name='imagen',
            field=models.ImageField(upload_to='files/'),
        ),
    ]
